---
- name: Create cgroups CPU configuration file
  copy:
    src: 99-cpu.conf
    dest: /etc/systemd/system/glusterd.service.d/99-cpu.conf

- name: Set CPU quota 
  template:
    src: glusterfs.slice.j2 
    dest: /etc/systemd/system/glusterfs.slice

- name: Restart glusterd
  service:
    name: glusterd
    state: restarted
